### ISSUE TITLE
Error login

### ISSUE THREAD

**Issue by ghost** [CIFP-Pau-Casesnoves-DAW/etv-public-tauladesfons#1]
Buenas, hemos intentado realizar el login para que me devuelva el token y no me devuelve nada, me devuelve este error:
"message": "SQLSTATE[42S22]: Column not found: 1054 Unknown column 'api_token' in 'field list' (SQL: update `USUARIS` set `api_token` = WWR6Q3k3WmE5UVVtd2k2YTUxWmVsWGxHanN5UFJtbVF2dHlpb0VyMA== where `ID_USUARI` = 5)",

**Comment by isaacpaloug** [comment]
Buenas, ese error ya esta solucionado en local, durante las proximas horas lo subire a remoto . Te avisaré👍

**Comment by ghost** [comment]
ya funciona correctamente, muchas gracias!!. Ahora seguiremos probando todo lo otro.

**Comment by isaacpaloug** [comment]
Buenas Francisco si tienes alguna duda importante puedes enviarme un correo electronico ya que las issues de github tatrdan mas en enviarte la notificacion. Gracias!

**Comment by isaacpaloug** [comment]
También recalcar que esta semana estamos muy apretados de trabajos y examenes y no podremos resolver las incidencias tan rápido como nos gustaría, pero no dudeis en aportar mejoras que creais necesarias y se iral resolviendo poco a poco.

A partir de la semana que viene seremos un poco mas libres y arreglaremos muchas cosas de la api para que la podais usar correctamente.
